[package]
name = "rust"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.19.0"
nannou_osc = "0.15.0"
rayon = "1.10.0"
std-dev = "0.1.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
